In [50]:
x0 = 0 #Se declara un vector x con las particiones del intervalo
x1 =(2/9)*pi
x2 =(4/9)*pi
x3 =(6/9)*pi
x4 =(8/9)*pi
x5 =(10/9)*pi
x6 =(12/9)*pi
x7 =(14/9)*pi
x8 =(16/9)*pi
x9 =(18/9)*pi
x = [x0,x1,x2,x3,x4,x5,x6,x7,x8,x9]

10-element Array{Float64,1}:
 0.0     
 0.698132
 1.39626 
 2.0944  
 2.79253 
 3.49066 
 4.18879 
 4.88692 
 5.58505 
 6.28319 

### Se definieron todos los multiplicadores

In [13]:
l0(x) = ((x-x1)/(x0-x1))*((x-x2)/(x0-x2))*((x-x3)/(x0-x3))*((x-x4)/(x0-x4))*((x-x5)/(x0-x5))*((x-x6)/(x0-x6))*((x-x7)/(x0-x7))*((x-x8)/(x0-x8))*((x-x9)/(x0-x9))

l0 (generic function with 1 method)

In [14]:
l1(x) = ((x-x0)/(x1-x0))*((x-x2)/(x1-x2))*((x-x3)/(x1-x3))*((x-x4)/(x1-x4))*((x-x5)/(x1-x5))*((x-x6)/(x1-x6))*((x-x7)/(x1-x7))*((x-x8)/(x1-x8))*((x-x9)/(x1-x9))

l1 (generic function with 1 method)

In [15]:
l2(x)= ((x-x0)/(x2-x0))*((x-x1)/(x2-x1))*((x-x3)/(x2-x3))*((x-x4)/(x2-x4))*((x-x5)/(x2-x5))*((x-x6)/(x2-x6))*((x-x7)/(x2-x7))*((x-x8)/(x2-x8))*((x-x9)/(x2-x9))

l2 (generic function with 1 method)

In [16]:
l3(x)= ((x-x0)/(x3-x0))*((x-x1)/(x3-x1))*((x-x2)/(x3-x2))*((x-x4)/(x3-x4))*((x-x5)/(x3-x5))*((x-x6)/(x3-x6))*((x-x7)/(x3-x7))*((x-x8)/(x3-x8))*((x-x9)/(x3-x9))

l3 (generic function with 1 method)

In [17]:
l4(x)= ((x-x0)/(x4-x0))*((x-x1)/(x4-x1))*((x-x2)/(x4-x2))*((x-x3)/(x4-x3))*((x-x5)/(x4-x5))*((x-x6)/(x4-x6))*((x-x7)/(x4-x7))*((x-x8)/(x4-x8))*((x-x9)/(x4-x9))

l4 (generic function with 1 method)

In [18]:
l5(x)= ((x-x0)/(x5-x0))*((x-x1)/(x5-x1))*((x-x2)/(x5-x2))*((x-x3)/(x5-x3))*((x-x4)/(x5-x4))*((x-x6)/(x5-x6))*((x-x7)/(x5-x7))*((x-x8)/(x5-x8))*((x-x9)/(x5-x9))

l5 (generic function with 1 method)

In [19]:
l6(x)= ((x-x0)/(x6-x0))*((x-x1)/(x6-x1))*((x-x2)/(x6-x2))*((x-x3)/(x6-x3))*((x-x4)/(x6-x4))*((x-x5)/(x6-x5))*((x-x7)/(x6-x7))*((x-x8)/(x6-x8))*((x-x9)/(x6-x9))

l6 (generic function with 1 method)

In [20]:
l7(x)= ((x-x0)/(x7-x0))*((x-x1)/(x7-x1))*((x-x2)/(x7-x2))*((x-x3)/(x7-x3))*((x-x4)/(x7-x4))*((x-x5)/(x7-x5))*((x-x6)/(x7-x6))*((x-x8)/(x7-x8))*((x-x9)/(x7-x9))

l7 (generic function with 1 method)

In [21]:
l8(x)= ((x-x0)/(x8-x0))*((x-x1)/(x8-x1))*((x-x2)/(x8-x2))*((x-x3)/(x8-x3))*((x-x4)/(x8-x4))*((x-x5)/(x8-x5))*((x-x6)/(x8-x6))*((x-x7)/(x8-x7))*((x-x9)/(x8-x9))

l8 (generic function with 1 method)

In [22]:
l9(x)= ((x-x0)/(x9-x0))*((x-x1)/(x9-x1))*((x-x2)/(x9-x2))*((x-x3)/(x9-x3))*((x-x4)/(x9-x4))*((x-x5)/(x9-x5))*((x-x6)/(x9-x6))*((x-x7)/(x9-x7))*((x-x8)/(x9-x8))

l9 (generic function with 1 method)

In [25]:
function yi(x) #Esta función genera un arreglo con las entradas de x
    y = zeros(1,10)
    for i in 1:10
        y[i] = cos(x[i])
    end
    return y
end

yi (generic function with 1 method)

In [51]:
function L(x,y)# Se define el polinomio de lagrange
    r = zeros(1,10)
    for i in 1:10
    z = x[i]  
    r[i] = y[1]*l0(z)+y[2]*l1(z)+y[3]*l2(z)+y[4]*l3(z)+y[5]*l4(z)+y[6]*l5(z)+y[7]*l6(z)+y[8]*l7(z)+y[9]*l8(z)+y[10]*l9(z)
    end
return r
end

L (generic function with 2 methods)

In [52]:
y=yi(x)

1×10 Array{Float64,2}:
 1.0  0.766044  0.173648  -0.5  -0.939693  …  -0.5  0.173648  0.766044  1.0

In [45]:
h = L(x,y) # Podemos ver que la interpolación tine los mismos valores que la función, porlotanto el método realiza muy buenas aproximaciones

1×10 Array{Float64,2}:
 1.0  0.766044  0.173648  -0.5  -0.939693  …  -0.5  0.173648  0.766044  1.0

In [47]:
function y2i(x) #se genero una función que genere arreglos con la función de coseno cuadrado
    y = zeros(1,10)
    for i in 1:10
        y[i] = cos(x[i])*cos(x[i])
    end
    return y
end

y2i (generic function with 1 method)

In [48]:
y2=y2i(x)

1×10 Array{Float64,2}:
 1.0  0.586824  0.0301537  0.25  0.883022  …  0.25  0.0301537  0.586824  1.0

In [49]:
L(x,y2)

1×10 Array{Float64,2}:
 1.0  0.586824  0.0301537  0.25  0.883022  …  0.25  0.0301537  0.586824  1.0